package relay

import (
	"context"
	"sync/atomic"
	"time"

	"github.com/bluenviron/mediacommon/v2/pkg/codecs/mpeg4audio"
)

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// Default values for SilenceAACGenerator.
const (
	DefaultSampleRate           = 48000
	DefaultChannels             = 2
	DefaultFrameDurationMs      = 100 // 10 fps
	DefaultMaxContinuousSilence = 5 * time.Second
)

// silenceAACFrame48kStereo is the pre-computed canonical silent AAC-LC raw
// access unit for 48 kHz stereo.  Generated by FFmpeg:
//
//	ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=48000 \
//	       -c:a aac -t 0.1 -f adts pipe:1
//
// The frame is the 2nd+ ADTS payload (6 bytes): the encoder emits a larger
// first AU (with encoder-string fill data), then 6-byte silent AUs.
var silenceAACFrame48kStereo = []byte{0x21, 0x10, 0x04, 0x60, 0x8c, 0x1c}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

// SilenceAACConfig configures a SilenceAACGenerator.  Zero values get defaults.
type SilenceAACConfig struct {
	SampleRate           int
	Channels             int
	FrameDurationMs      int
	MaxContinuousSilence time.Duration
}

func (c SilenceAACConfig) sampleRate() int {
	if c.SampleRate > 0 {
		return c.SampleRate
	}
	return DefaultSampleRate
}

func (c SilenceAACConfig) channels() int {
	if c.Channels > 0 {
		return c.Channels
	}
	return DefaultChannels
}

func (c SilenceAACConfig) frameDurationMs() int {
	if c.FrameDurationMs > 0 {
		return c.FrameDurationMs
	}
	return DefaultFrameDurationMs
}

func (c SilenceAACConfig) maxContinuousSilence() time.Duration {
	if c.MaxContinuousSilence > 0 {
		return c.MaxContinuousSilence
	}
	return DefaultMaxContinuousSilence
}

// ---------------------------------------------------------------------------
// SilenceAACGenerator
// ---------------------------------------------------------------------------

// SilenceAACGenerator emits pre-computed silent AAC-LC frames at a configurable
// rate via a channel.  It auto-stops after MaxContinuousSilence (default 5s)
// unless SourceActive() is called to reset the silence timer.  Channel sends
// are non-blocking — the producer never blocks on a full channel.
//
// Typical use: provide a silent audio track when the source camera has no audio,
// so that downstream consumers (RTMP targets, HLS) always have an audio stream.
type SilenceAACGenerator struct {
	sampleRate           int
	channels             int
	frameDurationMs      int
	maxContinuousSilence time.Duration

	precomputedFrame []byte
	configBytes      []byte

	// lastActive stores the UnixNano timestamp of the last SourceActive() call.
	// Accessed atomically from the producer goroutine.
	lastActive atomic.Int64

	cancel context.CancelFunc
}

// NewSilenceAACGenerator creates a generator with default configuration
// (48 kHz stereo, 10 fps, 5 s auto-stop timeout).
func NewSilenceAACGenerator() *SilenceAACGenerator {
	return NewSilenceAACGeneratorWith(SilenceAACConfig{})
}

// NewSilenceAACGeneratorWith creates a generator with the provided config.
// Zero-valued fields are replaced by defaults.
func NewSilenceAACGeneratorWith(cfg SilenceAACConfig) *SilenceAACGenerator {
	sr := cfg.sampleRate()
	ch := cfg.channels()

	asc := mpeg4audio.AudioSpecificConfig{
		Type:          mpeg4audio.ObjectTypeAACLC,
		SampleRate:    sr,
		ChannelConfig: uint8(ch),
		ChannelCount:  ch,
	}
	configBytes, err := asc.Marshal()
	if err != nil {
		// Should never happen for a valid AAC-LC config.
		panic("SilenceAACGenerator: AudioSpecificConfig.Marshal failed: " + err.Error())
	}

	return &SilenceAACGenerator{
		sampleRate:           sr,
		channels:             ch,
		frameDurationMs:      cfg.frameDurationMs(),
		maxContinuousSilence: cfg.maxContinuousSilence(),

		precomputedFrame: silenceAACFrame48kStereo,
		configBytes:      configBytes,
	}
}

// Start begins emitting one silent AAC-LC frame every FrameDurationMs on the
// returned channel.  The generator runs until one of:
//   - ctx is cancelled
//   - Stop() is called
//   - MaxContinuousSilence elapses without a SourceActive() call
//
// The channel is closed when emission stops.  Sends are non-blocking — the
// producer goroutine drops frames if the channel buffer is full.
func (g *SilenceAACGenerator) Start(ctx context.Context) <-chan []byte {
	ctx, g.cancel = context.WithCancel(ctx)
	ch := make(chan []byte, 10)

	g.lastActive.Store(time.Now().UnixNano())

	go g.run(ctx, ch)

	return ch
}

// Stop cancels generation and closes the channel.  Safe to call multiple times.
func (g *SilenceAACGenerator) Stop() {
	if g.cancel != nil {
		g.cancel()
	}
}

// SourceActive resets the silence timeout.  Call this when the audio source
// is known to be active (e.g. when video frames arrive) to prevent the
// generator from auto-stopping.
func (g *SilenceAACGenerator) SourceActive() {
	g.lastActive.Store(time.Now().UnixNano())
}

// Config returns the AudioSpecificConfig marshaled bytes for the generator's
// configuration (AAC-LC, configured sample rate, configured channels).
func (g *SilenceAACGenerator) Config() []byte {
	return g.configBytes
}

// ---------------------------------------------------------------------------
// internal
// ---------------------------------------------------------------------------

func (g *SilenceAACGenerator) run(ctx context.Context, ch chan []byte) {
	defer close(ch)

	ticker := time.NewTicker(time.Duration(g.frameDurationMs) * time.Millisecond)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return

		case <-ticker.C:
			// Check silence timeout.
			if time.Since(time.Unix(0, g.lastActive.Load())) > g.maxContinuousSilence {
				return
			}
			// Non-blocking send — drop frame if channel is full.
			select {
			case ch <- g.precomputedFrame:
			default:
			}
		}
	}
}
